[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
contract-client = { git = "https://github.com/subsquid/subsquid-network.git", rev = "8df33fe" }
subsquid-messages = { git = "https://github.com/subsquid/subsquid-network.git", rev = "8df33fe" }
subsquid-network-transport = { git = "https://github.com/subsquid/subsquid-network.git", rev = "8df33fe" }
