[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
subsquid-messages = { git = "ssh://git@github.com/subsquid/subsquid-network.git", rev = "4753ce6" }
subsquid-network-transport = { git = "ssh://git@github.com/subsquid/subsquid-network.git", rev = "4753ce6" }
