[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
contract-client = { git = "ssh://git@github.com/subsquid/subsquid-network.git", version = "1.0.0-rc1" }
subsquid-messages = { git = "ssh://git@github.com/subsquid/subsquid-network.git", version = "1.0.0-rc1" }
subsquid-network-transport = { git = "ssh://git@github.com/subsquid/subsquid-network.git", version = "1.0.0-rc1" }
