[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
contract-client = { git = "https://github.com/subsquid/subsquid-network.git", version = "1.0.5" }
subsquid-messages = { git = "https://github.com/subsquid/subsquid-network.git", version = "1.1.2" }
subsquid-network-transport = { git = "https://github.com/subsquid/subsquid-network.git", version = "1.0.17" }
