logs_collector_id: "12D3KooWC3GvQVqnvPwWz23sTW8G8HVokMnox62A7mnL9wwaSujk"
send_metrics: true
worker_inactive_threshold_sec: 120
worker_greylist_time_sec: 1800
default_query_timeout_sec: 60
summary_print_interval_sec: 30
workers_update_interval_sec: 180
available_datasets:
  ethereum-mainnet: "czM6Ly9ldGhlcmV1bS1tYWlubmV0LTE"
  binance-mainnet: "czM6Ly9ic2MtbWFpbm5ldC0x"
  base-mainnet: "czM6Ly9iYXNlLTE"
  moonbeam-mainnet: "czM6Ly9tb29uYmVhbS1ldm0tMQ"
