[package]
name = "logs-collector"
version = "0.2.9"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive", "env"] }
clickhouse = "0.11"
env_logger = "0.11"
futures = "0.3"
log = "0.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_bytes = "0.11"
serde_repr = "0.1"
tokio = { version = "1", features = ["full"] }

contract-client = { version = "0.1", path = "../contract-client" }
subsquid-messages = { version = "0.1", path = "../messages", features = ["signatures"] }
subsquid-network-transport = { git = "ssh://git@github.com/subsquid/subsquid-network.git", rev = "ffdd912" }
