[package]
name = "router-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21"
log = "0.4"
parking_lot = "0.12"
rand = "0.8"
serde = "1"

sqd-messages = { workspace = true } # FIXME: Remove this dependency
