[package]
name = "router-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
parking_lot = "0.12.1"
rand = "0.8.5"
serde = { version = "1.0.147", features = ["derive"] }
log = "0.4"
