name: network-docker
on:
  workflow_dispatch: # manually run
    inputs:
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: Build & publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load ssh key to fetch private dependencies
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.NETWORK_SSH_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build scheduler
        uses: docker/build-push-action@v5
        with:
          context: .
          target: network-scheduler
          load: true
          tags: subsquid/network-scheduler:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get scheduler version
        run: echo "SCHEDULER_VERSION=$(docker run --rm subsquid/network-scheduler:test network-scheduler --version | cut -d ' ' -f2)" >> $GITHUB_ENV

      - name: Build & publish scheduler
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          target: network-scheduler
          push: true
          tags: |
            subsquid/network-scheduler:${{ env.SCHEDULER_VERSION }}
            subsquid/network-scheduler:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build query gateway
        uses: docker/build-push-action@v5
        with:
          context: .
          target: query-gateway
          load: true
          tags: subsquid/query-gateway:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get query gateway version
        run: echo "GATEWAY_VERSION=$(docker run --rm subsquid/query-gateway:test query-gateway --version | cut -d ' ' -f2)" >> $GITHUB_ENV

      - name: Build & publish query gateway
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          target: query-gateway
          push: true
          tags: |
            subsquid/query-gateway:${{ env.GATEWAY_VERSION }}
            subsquid/query-gateway:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build logs collector
        uses: docker/build-push-action@v5
        with:
          context: .
          target: logs-collector
          load: true
          tags: subsquid/logs-collector:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get logs collector version
        run: echo "COLLECTOR_VERSION=$(docker run --rm subsquid/logs-collector:test logs-collector --version | cut -d ' ' -f2)" >> $GITHUB_ENV

      - name: Build & publish logs collector
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          target: logs-collector
          push: true
          tags: |
            subsquid/logs-collector:${{ env.COLLECTOR_VERSION }}
            subsquid/logs-collector:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
