name: traffic-gen-docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: Build & publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & publish traffic generatpr
        uses: docker/build-push-action@v5
        with:
          context: ./scripts/traffic_generator
          platforms: linux/amd64
          push: true
          tags: |
            subsquid/traffic-generator:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
